# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-12 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='ocr_output',
            field=models.TextField(blank=True),
        ),
    ]
